In [19]:
import numpy as np
import pandas as pd

file_path = r"C:\Users\SK\Desktop\New folder\student performance.csv"

# Dataset
df = pd.read_csv(file_path)
df.head()



,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75


In [21]:
# Check structure
print(df.head())
print("\nShape of DataFrame:", df.shape)

# Extract numeric columns for arrays
math = df["math score"].to_numpy()
reading = df["reading score"].to_numpy()
writing = df["writing score"].to_numpy()

# One-dimensional arrays
print("\n=== 1D Arrays ===")
print("Math scores   → shape:", math.shape, "| ndim:", math.ndim, "| size:", math.size, "| dtype:", math.dtype)
print("Reading scores → shape:", reading.shape)
print("Writing scores → shape:", writing.shape)

# Two-dimensional array
scores_2d = df[["math score", "reading score", "writing score"]].to_numpy()
print("\n=== 2D Array ===")
print("scores_2d → shape:", scores_2d.shape, "| ndim:", scores_2d.ndim, "| size:", scores_2d.size, "| dtype:", scores_2d.dtype)
print(scores_2d[:5])   # first 5 rows

   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74  
1               completed          69             90             88  
2                    none          90             95             93  
3                    none          47             57             44  
4                    none          76             78             75  

Shape of DataFrame: (1000, 8)

=== 1D Arrays ===
Math scores   → shape: (1000,) | ndim: 1 | size: 1000 | dtype: int64
Reading scores → shape: (1000,)
Writing 

In [23]:
# Extract numeric columns for arrays
math = df["math score"].to_numpy()
reading = df["reading score"].to_numpy()
writing = df["writing score"].to_numpy()

# One-dimensional arrays
print("1D Math scores array:")
print(math)
print("Shape:", math.shape, "| ndim:", math.ndim, "| size:", math.size, "| dtype:", math.dtype)

print("\n1D Reading scores array:")
print(reading[:10], "...")  # first 10 for brevity
print("Shape:", reading.shape, "| ndim:", reading.ndim, "| size:", reading.size, "| dtype:", reading.dtype)

# Two-dimensional array (all three scores side-by-side)
scores_2d = df[["math score", "reading score", "writing score"]].to_numpy()
print("\n2D Scores array (math | reading | writing):")
print(scores_2d[:5])  # first 5 rows
print("Shape:", scores_2d.shape, "| ndim:", scores_2d.ndim, "| size:", scores_2d.size, "| dtype:", scores_2d.dtype)

1D Math scores array:
[ 72  69  90  47  76  71  88  40  64  38  58  40  65  78  50  69  88  18
  46  54  66  65  44  69  74  73  69  67  70  62  69  63  56  40  97  81
  74  50  75  57  55  58  53  59  50  65  55  66  57  82  53  77  53  88
  71  33  82  52  58   0  79  39  62  69  59  67  45  60  61  39  58  63
  41  61  49  44  30  80  61  62  47  49  50  72  42  73  76  71  58  73
  65  27  71  43  79  78  65  63  58  65  79  68  85  60  98  58  87  66
  52  70  77  62  54  51  99  84  75  78  51  55  79  91  88  63  83  87
  72  65  82  51  89  53  87  75  74  58  51  70  59  71  76  59  42  57
  88  22  88  73  68 100  62  77  59  54  62  70  66  60  61  66  82  75
  49  52  81  96  53  58  68  67  72  94  79  63  43  81  46  71  52  97
  62  46  50  65  45  65  80  62  48  77  66  76  62  77  69  61  59  55
  45  78  67  65  69  57  59  74  82  81  74  58  80  35  42  60  87  84
  83  34  66  61  56  87  55  86  52  45  72  57  68  88  76  46  67  92
  83  80  63  64  54  84  73 

In [25]:
print("=== Array Attributes ===")
print(f"math.shape   = {math.shape}")      # (1000,)
print(f"math.ndim    = {math.ndim}")       # 1
print(f"math.size    = {math.size}")       # 1000
print(f"math.dtype   = {math.dtype}")      # int64

print(f"\nscores_2d.shape = {scores_2d.shape}")  # (1000, 3)
print(f"scores_2d.ndim  = {scores_2d.ndim}")     # 2
print(f"scores_2d.size  = {scores_2d.size}")     # 3000
print(f"scores_2d.dtype = {scores_2d.dtype}")    # int64

=== Array Attributes ===
math.shape   = (1000,)
math.ndim    = 1
math.size    = 1000
math.dtype   = int64

scores_2d.shape = (1000, 3)
scores_2d.ndim  = 2
scores_2d.size  = 3000
scores_2d.dtype = int64


In [27]:
# Element-wise arithmetic
total = math + reading + writing
average = total / 3

print("First 5 total scores:", total[:5])
print("First 5 averages   :", np.round(average[:5], 2))

# Statistical operations
print("\nMath score stats:")
print(f"  Mean   : {np.mean(math):.2f}")
print(f"  Median : {np.median(math):.2f}")
print(f"  Std    : {np.std(math):.2f}")
print(f"  Min    : {np.min(math)}")
print(f"  Max    : {np.max(math)}")

# Boolean masking / filtering
high_math = math[math >= 80]
print(f"\nNumber of students with math ≥ 80: {len(high_math)}")
print("Their scores:", high_math[:10], "...")

# Comparison with pure Python lists (performance & syntax)
py_list = math.tolist()
# NumPy is vectorized – much faster and cleaner for large data
print("\nNumPy mean:", np.mean(math))
print("Python mean (manual):", sum(py_list)/len(py_list))

First 5 total scores: [218 247 278 148 229]
First 5 averages   : [72.67 82.33 92.67 49.33 76.33]

Math score stats:
  Mean   : 66.09
  Median : 66.00
  Std    : 15.16
  Min    : 0
  Max    : 100

Number of students with math ≥ 80: 193
Their scores: [90 88 88 97 81 82 88 82 80 85] ...

NumPy mean: 66.089
Python mean (manual): 66.089


In [29]:
# 1D array
arr1d = np.array([72, 69, 90, 47, 76])
print("1D example:", arr1d, "| shape:", arr1d.shape, "| dtype:", arr1d.dtype)

# 2D array
arr2d = np.array([
    [72, 72, 74],
    [69, 90, 88],
    [90, 95, 93]
])
print("\n2D example:\n", arr2d)
print("shape:", arr2d.shape, "| ndim:", arr2d.ndim, "| size:", arr2d.size)

# Other useful creation methods
zeros = np.zeros((3, 3))
ones  = np.ones((2, 4), dtype=np.int32)
arange = np.arange(0, 100, 10)
linspace = np.linspace(0, 1, 5)

print("\nzeros:\n", zeros)
print("ones:\n", ones)
print("arange:", arange)
print("linspace:", linspace)

1D example: [72 69 90 47 76] | shape: (5,) | dtype: int32

2D example:
 [[72 72 74]
 [69 90 88]
 [90 95 93]]
shape: (3, 3) | ndim: 2 | size: 9

zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1 1 1 1]
 [1 1 1 1]]
arange: [ 0 10 20 30 40 50 60 70 80 90]
linspace: [0.   0.25 0.5  0.75 1.  ]
